const QandAList = [
  {
    number: "1",
    type: "E/I",
    question: "E인지 I 인지 선택하는 첫 번째 질문입니다.",
    firstAnswer: "당신은 E",
    secondAnswer: "당신은 I",
  },
  {
    number: "2",
    type: "E/I",
    question: "E인지 I 인지 선택하는 두 번째 질문입니다.",
    firstAnswer: "당신은 E",
    secondAnswer: "당신은 I",
  },
  {
    number: "3",
    type: "E/I",
    question: "E인지 I 인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 E",
    secondAnswer: "당신은 I",
  },
  {
    number: "4",
    type: "N/S",
    question: "N인지 S인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 N",
    secondAnswer: "당신은 S",
  },
  {
    number: "5",
    type: "N/S",
    question: "N인지 S인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 N",
    secondAnswer: "당신은 S",
  },
  {
    number: "6",
    type: "N/S",
    question: "N인지 S인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 N",
    secondAnswer: "당신은 S",
  },
  {
    number: "7",
    type: "F/T",
    question: "F인지 T인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 F",
    secondAnswer: "당신은 T",
  },
  {
    number: "8",
    type: "F/T",
    question: "F인지 T인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 F",
    secondAnswer: "당신은 T",
  },
  {
    number: "9",
    type: "F/T",
    question: "F인지 T인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 F",
    secondAnswer: "당신은 T",
  },
  {
    number: "10",
    type: "J/P",
    question: "J인지 P인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 J",
    secondAnswer: "당신은 P",
  },
  {
    number: "11",
    type: "J/P",
    question: "J인지 P인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 J",
    secondAnswer: "당신은 P",
  },
  {
    number: "12",
    type: "J/P",
    question: "J인지 P인지 선택하는 세 번째 질문입니다.",
    firstAnswer: "당신은 J",
    secondAnswer: "당신은 P",
  },
];
